// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// HttpAdapter is an autogenerated mock type for the HttpAdapter type
type HttpAdapter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *HttpAdapter) Delete(_a0 string, _a1 map[string]string) (*http.Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, map[string]string) *http.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *HttpAdapter) Get(_a0 string, _a1 map[string]string) (*http.Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, map[string]string) *http.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Post provides a mock function with given fields: _a0, _a1, _a2
func (_m *HttpAdapter) Post(_a0 string, _a1 interface{}, _a2 map[string]string) (*http.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, interface{}, map[string]string) *http.Response); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, interface{}, map[string]string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Put provides a mock function with given fields: _a0, _a1, _a2
func (_m *HttpAdapter) Put(_a0 string, _a1 interface{}, _a2 map[string]string) (*http.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, interface{}, map[string]string) *http.Response); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, interface{}, map[string]string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
