#!/bin/bash

set -ex

APP="themekit"
VERSION=$(eval git describe --tags --abbrev=0)

target="deb/usr/local/${APP}"
mkdir -p ${target}

cp ./build/dist/linux-amd64/theme ${target}

bundle exec fpm -s dir -t deb -n ${APP} -v "$VERSION" -C deb -p build/dist/themekit.deb .

rm -rf deb
