#!/usr/bin/python
import os
import urllib
import json

class Installer(object):
    INSTALL_PATH = "/usr/local/bin/theme"
    LATEST_RELEASE_URL = "https://shopify-themekit.s3.amazonaws.com/releases/latest.json"
    ARCH_MAPPING = {
        "darwin x86_64": "darwin-amd64",
        "linux x86_64": "linux-amd64",
        "linux i686": "linux-386"
    }

    def install(self):
        print("Fetching release data")
        release = self.__fetchRelease()
        print("Downloading version %s of Shopify Themekit" % release['version'])
        self.__download(release)
        print("Theme Kit has been installed at %s" % Installer.INSTALL_PATH)
        print('To verify themekit is working simply type "theme"')

    def __getArch(self):
        pipe = os.popen("echo \"$(uname) $(uname -m)\"")
        arch_name = pipe.readline().strip().lower()
        pipe.close()
        return Installer.ARCH_MAPPING[arch_name]

    def __findReleaseURL(self, release):
        arch = self.__getArch()
        for index, platform in enumerate(release['platforms']):
            if platform['name'] == arch:
                return platform['url']

    def __fetchRelease(self):
        return json.loads(urllib.urlopen(Installer.LATEST_RELEASE_URL).read().decode("utf-8"))

    def __download(self, release):
        data = urllib.urlopen(self.__findReleaseURL(release)).read()
        with open(Installer.INSTALL_PATH, "wb") as themefile:
            themefile.write(data)
        os.chmod(Installer.INSTALL_PATH, 0o755)

Installer().install()
