#!/usr/bin/env ruby
# frozen_string_literal: true
require 'fog/aws'
require 'dotenv'
require 'json'
require_relative './themekit_release/themekit_release.rb'

Dotenv.load

puts 'Establishing Connection to Amazon S3'
connection = Fog::Storage.new(
  provider: 'AWS',
  aws_access_key_id: ENV['AWS_KEY_ID'],
  aws_secret_access_key: ENV['AWS_SECRET_KEY']
)

bucket = Fog::Storage::AWS::Directory.new(
  key: ENV['AWS_BUCKET_NAME'],
  service: connection
)

puts 'Determining latest release'
repo = Repository.new
version = repo.latest_version

manager = FileManager.new(bucket)

release_generator = ReleaseGenerator.new(version, manager)
puts "Uploading releases for #{version} to S3"
release_generator.upload!

feed_generator = FeedGenerator.new(version, release_generator.releases, manager)
puts 'Updating feeds'
feed_generator.upload!
